Example for __call__
trag1c/mcoding-all-dunders pull request #11
Opened 2023-04-18 12:55 UTC by edsaac

Creates an Appliance object that can be either on or off. 

Each time the object is called as a function, it's state switches and a message is returned.  
Calling just the object will go through the `__repr__` dunder

2023-04-18 16:05 UTC, trag1c requested changes
I don't see why `switch` is its own method if it's only used in `__call__`

2023-04-18 16:50 UTC, edsaac commented on src/middle-earth/call.py
> +    print(f"{bool(pc) =:}")  # __bool__
Without the colon, the escape characters in the returned string are not escaped. 

|Case|Command|Output|
|:---|:----|:-----|
|Without `:` | `print{f"{tv() =}")`  | `tv() ='\tThe room TV is ON\t(from __call__)'` |
|With `:`       | `print{f"{tv() =:})"` | `tv() =  The room TV is ON       (from __call__) `|

2023-04-18 16:53 UTC, edsaac commented on src/middle-earth/call.py
> +    print(f"{bool(pc) =:}")  # __bool__
Maybe that could be an example for `__format__`

2023-04-18 16:56 UTC, edsaac commented on src/middle-earth/call.py
> +    print(f"{bool(pc) =:}")  # __bool__
Maybe that could be an example for `__format__`  ?

2023-04-18 17:01 UTC, trag1c commented on src/middle-earth/call.py
> +    print(f"{bool(pc) =:}")  # __bool__
TIL! I always used `f"{x = !s}"` for that:
```pycon
>>> x = "hello\tthere"
>>> print(f"{x = }")
x = 'hello\tthere'
>>> print(f"{x = !s}")
x = hello	there
```

2023-04-18 17:01 UTC, trag1c commented on src/middle-earth/call.py
> +    print(f"{bool(pc) =:}")  # __bool__
> Maybe that could be an example for `__format__`

Maybe maybe

2023-04-21 03:22 UTC, Lunarmagpie commented
I think a better example for call is mimicking `functools.partial`. People probably wonder how that works as well.

2023-04-21 03:42 UTC, MithicSpirit requested changes
Please format with black.

2023-04-21 03:42 UTC, MithicSpirit commented on src/middle-earth/call.py
> +        return self.status() + "\t(from __repr__)"
I think that an fstring would be better than string concatenation. Also not too sure on the use of tabs here. Please discuss.

2023-04-21 15:05 UTC, CircuitSacul requested changes

2023-04-21 15:05 UTC, CircuitSacul commented on src/middle-earth/call.py
> +    print(f"{bool(pc) = }")  # __bool__
This is always True since you haven't implemented `__bool__`

2023-04-21 15:08 UTC, edsaac commented on src/middle-earth/call.py
> +    print(f"{bool(pc) = }")  # __bool__
But `__bool__` is already implemented :thinking:

2023-04-21 15:09 UTC, CircuitSacul commented on src/middle-earth/call.py
> +    print(f"{bool(pc) = }")  # __bool__
Yes, the default behavior is to return True. I assume it was supposed to return True if the appliance is on and False if the appliance is off, in which case you would need to override it?

2023-04-21 15:10 UTC, CircuitSacul commented on src/middle-earth/call.py
> +    print(f"{bool(pc) = }")  # __bool__
Nevermind I'm blind

2023-05-04 06:32 UTC, trag1c requested changes

2023-05-04 06:32 UTC, trag1c commented on src/middle-earth/call.py
> +    def __init__(self, name: str, is_on: bool = False) -> None:
```suggestion
    def __init__(self, name: str, *, is_on: bool = False) -> None:
```

2023-05-04 11:29 UTC, edsaac commented
The `functools.partial` idea sounds better than this dummy example. I'm closing this PR so `__call__`  can be returned to  the TO DO list on the tracking spreadsheet.

2023-05-04 11:29 UTC, closed without merging