Inheritance Tree Dunders
trag1c/mcoding-all-dunders pull request #19
Opened 2023-04-20 21:23 UTC by FuexFollets

Dunders `__base__`, `__bases__`, `__subclass__`

Examples are shown as molecules

2023-04-21 03:19 UTC, Lunarmagpie requested changes

2023-04-21 03:19 UTC, Lunarmagpie commented on src/meta-plane/inheritance_tree.py
> +    # if two methods have the same nade
```suggestion
    # The MRO (method resolution order) is decided by checking the
    # `__bases__` array from left to right.
```
Not sure if line length is good

2023-04-21 03:56 UTC, MithicSpirit requested changes
This seems like an improper use of inheritance as it leads to nonsensical polymorphism. If I make a function that takes in an `Oxygen` it doesn't make sense to get a `Water`. If you want to keep the physics theme maybe do something with fundamental particles (maybe something like `Quark()`, `Antiquark(Quark)`, `UpQuark(Quark)`, `RedUpQuark(UpQuark)`, `AntiRedUpQuark(RedUpQuark, Antiquark)`, although the names might be a bit much).

2023-04-21 14:05 UTC, FuexFollets commented on src/meta-plane/inheritance_tree.py
> +    # if two methods have the same nade
Although, this is determined by `__mro__` rather than `__bases__`. I'm going to change the comment to something else still

2023-06-27 00:21 UTC, FuexFollets commented
(This one is ready for review btw)

2023-06-27 00:23 UTC, trag1c commented
What's the point of having `get_class_name` methods if they're not used? 🤔

2023-06-27 00:39 UTC, FuexFollets commented
haha, good point

2023-06-27 19:34 UTC, CircuitSacul approved these changes

2023-07-19 21:14 UTC, MithicSpirit approved these changes
lgtm.

2023-07-19 21:30 UTC, trag1c commented
How do you feel about including an `__mro__` example for the `Ant` class?

2023-07-22 00:24 UTC, trag1c approved these changes

2023-07-22 00:24 UTC, merged