Example for `__format__` ft. f-strings
trag1c/mcoding-all-dunders pull request #21
Opened 2023-05-04 03:09 UTC by edsaac

_Problem:_
For an integer, `f"{10:b}"` returns `'1010'` :)
For a float, `f"{10.0:b}"` raises a `ValueError` :(

_Goal:_
`f"{10.0:b}"` returns the string of 32bits `01000001001000000000000000000000`

_Solution:_
Defined a class that inherits from `float` and implements a format specification for binary. 

______

Not sure if inheriting from `float` was done correctly.

2023-05-04 06:27 UTC, trag1c commented
Make black happy :)

2023-05-04 14:12 UTC, qexat requested changes

2023-05-04 14:12 UTC, qexat commented on src/middle-earth/format.py
> +        ...
You probably should do something in handling the exception instead of leaving an ellipsis, but if you don't, you probably want to use `contextlib.suppress` context manager:

```py
with contextlib.suppress(OverflowError):
    print(f"{num:b}")
```

I would not recommend that though, instead you probably should either re-raise the exception or raise a related one with contextual information.

2023-05-04 14:12 UTC, qexat commented on src/middle-earth/format.py
> +    print(f"{binfloat=} is {type(binfloat)}.\nIn binary, {binfloat=:b}")
perhaps `type(binfloat).__name__`? would print more nicely, imo.

2023-05-04 14:12 UTC, qexat commented on src/middle-earth/format.py
> +    binfloat = BinarizableFloat(0.15625)
why not writing `BinarizableFloat(float_num)` instead?

2023-05-04 15:17 UTC, edsaac commented on src/middle-earth/format.py
> +        ...
Replaced all these with unit tests. That `try` block in particular was replaced with an `assertRaises`.

2023-05-04 16:15 UTC, qexat commented
Not really fond of the `unittest` usage ngl

2023-05-04 16:49 UTC, trag1c commented
> Not really fond of the `unittest` usage ngl

That lib sucks :trollface:

2023-05-09 02:19 UTC, edsaac commented on src/middle-earth/format.py
> +    print(f"{binfloat=} is {type(binfloat)}.\nIn binary, {binfloat=:b}")
It prints more nicely indeed

2023-06-21 03:59 UTC, trag1c approved these changes

2023-06-25 22:24 UTC, isFakeAccount commented
`bytes = pack(">f", self)` should return big-endian according to the URL. No?

https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment.

2023-06-25 22:46 UTC, trag1c commented on src/middle-earth/format.py
> +        return super(BinarizableFloat, cls).__new__(cls, val)
```suggestion
        return super().__new__(cls, val)
```

2023-06-26 01:33 UTC, isFakeAccount requested changes

2023-06-26 01:33 UTC, isFakeAccount commented on src/middle-earth/format.py
> +    def __new__(cls, val, *args, **kwargs):
Please use `__init__()` here instead of `__new__()`

2023-06-26 01:33 UTC, isFakeAccount commented on src/middle-earth/format.py
> +        - Byte order is fixed to little-endian.
I think you meant Big Endian here. According to this https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment

2023-06-26 01:36 UTC, trag1c commented on src/middle-earth/format.py
> +    def __new__(cls, val, *args, **kwargs):
There is no need for any method. These 2 lines can be completely removed.

2023-06-26 01:51 UTC, isFakeAccount commented on src/middle-earth/format.py
> +    def __new__(cls, val, *args, **kwargs):
> There is no need for any method. These 2 lines can be completely removed.

Ok

2023-07-06 22:22 UTC, isFakeAccount approved these changes
LGTM :letsgo:

2023-07-06 22:29 UTC, merged