`__invert__`  on a RGB color
trag1c/mcoding-all-dunders pull request #22
Opened 2023-05-05 15:40 UTC by edsaac

Define a `PrimaryColor` class which holds a value between [0,255] and it's inverse is defined as the complement to 255. 

An `RGBColor` instance holds three `PrimaryColor`s and it's inverse is another `RGBColor` with each `PrimaryColor` inverted. 
___ 

Could make a matplotlib figure to show the colors and their inverse values nicely but not sure if we are doing imports outside the standard library.

2023-05-07 20:43 UTC, trag1c requested changes

2023-05-07 20:43 UTC, trag1c commented on src/math-land/invert.py
> +        self.check_valid()
I don't see why `check_valid` is its own method if it's only used here

2023-05-07 20:43 UTC, trag1c commented on src/math-land/invert.py
> +    __slots__ = "value"
TIL you can do that instead of `__slots__ = ("value",)` :)

2023-05-07 20:43 UTC, trag1c commented on src/math-land/invert.py
> +    print(f"{orange=:}, ", f"{antiorange=:}")
Why not make those one string?

2023-05-07 20:43 UTC, trag1c commented on src/math-land/invert.py
> +        return f"{self.value}"
Maybe `str(self.value)` instead?

2023-05-07 20:43 UTC, trag1c commented on src/math-land/invert.py
> +    def __invert__(self):
Be consistent with adding typehints

2023-05-07 23:57 UTC, edsaac commented on src/math-land/invert.py
> +    def __invert__(self):
Should that type hint be `def __invert__(self) -> Self:` or `def __invert__(self) -> "PrimaryColor":` ?

2023-05-08 00:01 UTC, edsaac commented on src/math-land/invert.py
> +    print(f"{orange=:}, ", f"{antiorange=:}")
At some point, there was something in between... fixed it.

2023-05-09 02:25 UTC, edsaac commented on src/math-land/invert.py
> +    def __invert__(self):
gotcha !

2023-05-09 02:37 UTC, trag1c requested changes

2023-05-09 02:37 UTC, trag1c commented on src/math-land/invert.py
> +        self.b = PrimaryColor(b) if isinstance(b, int) else b
Include `PrimaryColor` in annotations for `r`, `g` and `b`.

2023-05-10 19:41 UTC, edsaac commented on src/math-land/invert.py
> +    __slots__ = "value"
According to the notes in the [docs](https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots), any non-string iterable can be passed to `__slots__`... but passing a string does work! :thinking:

2023-05-10 19:44 UTC, trag1c commented on src/math-land/invert.py
> +    __slots__ = "value"
Yeah my guess is it works somewhat like this:
```py
def validate_slots(slots: object) -> Iterable[str]:
    if not isinstance(slots, Iterable):
        raise TypeError
    return (slots,) if isinstance(slots, str) else slots
```

2023-05-10 20:17 UTC, trag1c commented on src/math-land/invert.py
> +            raise ValueError("Color value is not between 0 and 255")
what about
```suggestion
        if not isinstance(value, int):
            raise TypeError("Color value must be an int")

        if not 0 <= value <= 255:
            raise ValueError("Color value is not between 0 and 255")

        self.value = value
```

2023-05-10 21:22 UTC, trag1c approved these changes

2023-06-19 18:09 UTC, MicaelJarniac requested changes

2023-06-19 18:09 UTC, MicaelJarniac commented on src/math-land/invert.py
> +            raise TypeError("Color value must be an int")
This check assumes that the type-hint isn't trustworthy.

However, on `RGBColor.__init__`, there's no such test.

IMO this makes it a bit inconsistent. I'd say to either remove this check from here or modify `RGBColor` so it also goes through the check.

2023-06-19 18:09 UTC, MicaelJarniac commented on src/math-land/invert.py
> +        self.b = PrimaryColor(b) if isinstance(b, int) else b
```suggestion
        self.r = r if isinstance(r, PrimaryColor) else PrimaryColor(r)
        self.g = g if isinstance(g, PrimaryColor) else PrimaryColor(g)
        self.b = b if isinstance(b, PrimaryColor) else PrimaryColor(b)
```

This makes it so that if a value of an incompatible type is passed, it goes through the checks in `PrimaryColor` and fails there.

I'd actually suggest making `PrimaryColor(PrimaryColor(2))` function so that this entire section could be just `self.r = PrimaryColor(r)` for each one, and it'd work similarly to some Python types like `int(int(5.3))`.

2023-06-19 18:46 UTC, trag1c commented on src/math-land/invert.py
> +        self.b = PrimaryColor(b) if isinstance(b, int) else b
> This makes it so that if a value of an incompatible type is passed, it goes through the checks in PrimaryColor and fails there.

I don't see how this is achieved?

> I'd actually suggest making `PrimaryColor(PrimaryColor(2))` function so that this entire section could be just `self.r = PrimaryColor(r)` for each one, and it'd work similarly to some Python types like `int(int(5.3))`.

"making it idempotent" is the term you're looking for :)

2023-06-19 19:53 UTC, trag1c commented on src/math-land/invert.py
> +        self.b = PrimaryColor(b) if isinstance(b, int) else b
Oh yeah that's right, I thought we were considering an "always `int` or `PrimaryColor`" case (should've made that clearer maybe 😅).

2023-06-19 20:04 UTC, MicaelJarniac commented on src/math-land/invert.py
> +        self.b = PrimaryColor(b) if isinstance(b, int) else b
IMO it does make sense to believe on the type-hint, but as I said on another comment, the code on `PrimaryColor` doesn't believe on the type-hint, and checks the type, so it'd be inconsistent IMO to have `PrimaryColor` care and `RGBColor` not care.

2023-06-21 13:48 UTC, edsaac commented on src/math-land/invert.py
> +        self.b = PrimaryColor(b) if isinstance(b, int) else b
That was definitively a test I was missing!

2023-06-27 19:32 UTC, CircuitSacul requested changes

2023-06-27 19:32 UTC, CircuitSacul commented on src/math-land/invert.py
> +            raise TypeError("Color value must be an int")
I agree, the check should be removed. That's the job of type-checkers, and there's no reason to force someone to use an object that's int-like, but wouldn't pass this test, if they really want to (python is dynamic and all that).

2023-07-05 15:26 UTC, CircuitSacul approved these changes

2023-07-05 17:16 UTC, MicaelJarniac requested changes

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
> +        return PrimaryColor(255 - self.value)
I'd suggest picking one of the following options (my preferred is the first):
### Create the same class as `self`
#### Using `type`
```suggestion
    def __invert__(self) -> Self:
        """
        Returns the inverse of the color as the complement to 255

        >>> print(~PrimaryColor(100))
        155
        """
        return type(self)(255 - self.value)
```
#### Using `__class__`
```suggestion
    def __invert__(self) -> Self:
        """
        Returns the inverse of the color as the complement to 255

        >>> print(~PrimaryColor(100))
        155
        """
        return self.__class__(255 - self.value)
```
### Return `PrimaryColor`
```suggestion
    def __invert__(self) -> "PrimaryColor":
        """
        Returns the inverse of the color as the complement to 255

        >>> print(~PrimaryColor(100))
        155
        """
        return PrimaryColor(255 - self.value)
```

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
Some docstrings have a space after them, some don't. I'd suggest being consistent - either always have a space, or never have it.

```py
def foo():
    """My docstring"""

    do_something()

def bar():
    """My docstring"""
    do_something()
```

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
> +
```suggestion
```

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
> +    __slots__ = "r", "g", "b"
```suggestion
    __slots__ = ("r", "g", "b")
```
To be consistent with the other class, that uses parens.

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
Some docstrings start on the same line as the opening quotes, while some start on the line below. I'd suggest being consistent.

```py
def foo():
    """My docstring

    Hello, world.
    """

def bar():
    """
    My docstring

    Hello, world.
    """
```

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
> +        Inititalize and check if the PrimaryColor has a valid value
```suggestion
        """Inititalize and check if the PrimaryColor has a valid value
```

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
> +        Returns the inverse of the color as the complement to 255
```suggestion
        """Returns the inverse of the color as the complement to 255
```

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
> +    A color in RGB space.
```suggestion
    """A color in RGB space
```
Notice I also removed the period at the end, to be consistent with the others.

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
> +        return RGBColor(~self.r, ~self.g, ~self.b)
I'd suggest picking one of the following options (my preferred is the first):
### Create the same class as `self`
#### Using `type`
```suggestion
    def __invert__(self) -> Self:
        """Calculate the inverse of each PrimaryColor and returns a new
        RGBColor

        >>> pink = RGBColor(255, 192, 203)
        >>> antipink = ~pink
        >>> print(antipink)
        (0, 63, 52)
        """
        return type(self)(~self.r, ~self.g, ~self.b)
```
#### Using `__class__`
```suggestion
    def __invert__(self) -> Self:
        """Calculate the inverse of each PrimaryColor and returns a new
        RGBColor

        >>> pink = RGBColor(255, 192, 203)
        >>> antipink = ~pink
        >>> print(antipink)
        (0, 63, 52)
        """
        return self.__class__(~self.r, ~self.g, ~self.b)
```
### Return `RGBColor`
```suggestion
    def __invert__(self) -> RGBColor:
        """Calculate the inverse of each PrimaryColor and returns a new
        RGBColor

        >>> pink = RGBColor(255, 192, 203)
        >>> antipink = ~pink
        >>> print(antipink)
        (0, 63, 52)
        """
        return RGBColor(~self.r, ~self.g, ~self.b)
```

2023-07-05 17:16 UTC, MicaelJarniac commented on src/math-land/invert.py
> +def main():
```suggestion
def main() -> None:
```

2023-07-05 18:16 UTC, edsaac commented on src/math-land/invert.py
> +        return PrimaryColor(255 - self.value)
What would be the issue with having `Self` in the typehint while directly returning a `PrimaryColor` instance?  Does `Self` indicate that the method returns the **same instance** or an instance of the **same class**?  I understand it as the latter.

2023-07-05 18:22 UTC, trag1c commented on src/math-land/invert.py
> +        return PrimaryColor(255 - self.value)
It indeed means the latter, which in consequence means that doing `return PrimaryColor(...)` makes it not hold in a subclass where it returns an instance of the parent class instead. That's solved by using `type(self)` or `self.__class__`.

2023-07-05 18:28 UTC, edsaac commented on src/math-land/invert.py
> +        return RGBColor(~self.r, ~self.g, ~self.b)
Same question [as above](https://github.com/trag1c/mcoding-all-dunders/pull/22#discussion_r1253467790) 🤔

2023-07-05 18:29 UTC, trag1c commented on src/math-land/invert.py
> +        return RGBColor(~self.r, ~self.g, ~self.b)
Same answer [as above](https://github.com/trag1c/mcoding-all-dunders/pull/22#discussion_r1253474427) :+1:

2023-07-05 18:29 UTC, edsaac commented on src/math-land/invert.py
They all start on the same line now.

2023-07-05 18:36 UTC, edsaac commented on src/math-land/invert.py
> +        return PrimaryColor(255 - self.value)
Aahh I see. Thanks!

2023-07-05 18:40 UTC, edsaac commented on src/math-land/invert.py
> +        return RGBColor(~self.r, ~self.g, ~self.b)
Same ❤️ as above

2023-07-05 18:47 UTC, MicaelJarniac commented
By the way, when someone leaves suggestions like I did, you can simply click on the "accept" button under the suggestion, and it automatically applies it, and I think it also credits the person that wrote the suggestion, as well as you.

2023-07-05 18:48 UTC, MicaelJarniac approved these changes

2023-07-05 18:52 UTC, trag1c commented
The suggester gets included as a co-author be exact 👍

2023-07-05 18:52 UTC, merged

2023-07-05 18:52 UTC, trag1c commented
Big thanks!