Added seval systems-swamp + `__file__` dunders
trag1c/mcoding-all-dunders pull request #24
Opened 2023-06-19 03:38 UTC by James-Ansley

Added dunders listed in #23  – with the exception of `__traceback__`, which I might come up with an example for later.

2023-06-19 16:05 UTC, trag1c commented on src/systems-swamp/stdio.py
> +def redirect_stdin(target: TextIO, write_to_stdout: bool = False):
```suggestion
def redirect_stdin(target: TextIO, *, write_to_stdout: bool = False) -> Iterator[None]:
```
\+ `from collections.abc import Iterator` please

2023-06-19 16:08 UTC, trag1c commented on src/systems-swamp/stdio.py
> +    sys.stderr = sys.__stderr__
```suggestion
@contextlib.contextmanager
def redirect_stdout(target: T) -> Iterator[T]:
    """Example only, use contextlib.redirect_stdout instead"""
    sys.stdout = target
    yield target
    sys.stdout = sys.__stdout__


@contextlib.contextmanager
def redirect_stderr(target: T) -> Iterator[T]:
    """Example only, use contextlib.redirect_stderr instead"""
    sys.stderr = target
    yield target
    sys.stderr = sys.__stderr__
```

2023-06-19 16:11 UTC, trag1c commented on src/systems-swamp/stdio.py
> +    return result
```suggestion
from typing import TextIO, TypeVar

T = TypeVar("T", bound=TextIO)

SAVED_INPUT = input


def _input(prompt: object) -> str:
    result = SAVED_INPUT(prompt)
    print(result)
    return result
```

2023-06-19 16:14 UTC, trag1c commented on src/systems-swamp/breakpointhook.py
> +    return z
Is the definition of `z` any useful for the example or can it just return `x + y`? 🤔

2023-06-20 00:41 UTC, James-Ansley commented on src/systems-swamp/breakpointhook.py
> +    return z
Since this example is about showing local variables in the debugger, I thought it would be more zesty and exciting if the function used more variables than just the parameters.

2023-06-20 00:42 UTC, trag1c commented on src/systems-swamp/breakpointhook.py
> +    return z
Okay, I'm asking since I wasn't able to see that when running the file (it's not like I'm experienced with this kinda stuff)

2023-06-20 00:53 UTC, James-Ansley commented on src/module-mesa/file/file.py
> +    print(f.read())
I prefer the `with` version – however, the suggestion uses the tab character. Is it possible to reformat it to use four spaces?

2023-06-20 00:58 UTC, trag1c commented on src/module-mesa/file/file.py
> +    print(f.read())
Yeah my bad, GitHub doesn't actually insert spaces when pressing <kbd>Tab</kbd>. 😔 I edited the message.

Why do you prefer the `with` version though if it actually does the exact same thing? 🤔

2023-06-20 00:58 UTC, James-Ansley commented on src/systems-swamp/displayhook.py
> +"""
I have updated the docstring.

2023-06-20 01:02 UTC, James-Ansley commented on src/module-mesa/file/file.py
> +    print(f.read())
I guess it's more familiar – drawing a box around some code saying, "_this_ is where the file is read". Feels more explicit than just throwing some paths around. Beyond that, I have no reason.

2023-06-20 01:10 UTC, James-Ansley commented on src/systems-swamp/stdio.py
> +def redirect_stdin(target: TextIO, write_to_stdout: bool = False):
Added in commit

2023-06-20 01:10 UTC, James-Ansley commented on src/systems-swamp/stdio.py
> +    sys.stderr = sys.__stderr__
Added in commit

2023-06-20 01:10 UTC, James-Ansley commented on src/systems-swamp/stdio.py
> +    return result
Added in commit

2023-06-20 11:40 UTC, trag1c requested changes

2023-06-20 11:40 UTC, trag1c commented on src/module-mesa/file/file.py
> +ASSETS = (Path(__file__) / ".." / "assets").resolve()
```suggestion
ASSETS = Path(__file__).parent / "assets"
```

2023-06-21 14:02 UTC, trag1c commented
@James-Ansley `excepthook.py` and `exceptions.py` still apply here:
> Improve the typehint inconsistencies across files (there are few which have typehints in some places and don't in other). From the submission guidelines:
> > * Be consistent about typehints: either do them properly or don't include them at all

2023-06-23 15:24 UTC, trag1c requested changes
For `exceptions.py` please annotate void functions with `-> None`

2023-06-23 15:24 UTC, trag1c commented on src/systems-swamp/excepthook.py
> +    type: Type[BaseException],
`typing.Type` is deprecated since 3.9, just use `type`

2023-06-23 22:35 UTC, trag1c approved these changes

2024-07-26 18:13 UTC, qexat approved these changes
This PR alone is one video lol

2024-11-19 08:09 UTC, closed without merging