Added the dunder str to repr.py and updated the file name
trag1c/mcoding-all-dunders pull request #27
Opened 2023-06-23 01:28 UTC by isFakeAccount

- Added the __str_() in the repr.py
- Updated the repr.py filename to str_and_repr.py
- Also added the .idea in gitirnore for jetbrain Ides

2023-06-23 03:07 UTC, trag1c reviewed
I think including `!a` would be nice too :)

2023-06-23 16:47 UTC, trag1c commented
It should be made clear that `!s` is the default specifier and that `f"{x!s}"` is equivalent to just `f"{x}"` :+1:

2023-06-23 19:04 UTC, isFakeAccount commented
crap, I forgot that it would add the fixed point file here

2023-06-23 19:34 UTC, trag1c commented
> crap, I forgot that it would add the fixed point file here

that's why you should use branches 💀💀💀

2023-06-23 20:07 UTC, isFakeAccount commented
Gone, Reduced to Atoms

2023-06-23 20:07 UTC, trag1c approved these changes

2023-06-23 20:10 UTC, isFakeAccount commented
wtf

2023-06-25 18:09 UTC, isFakeAccount commented
#29 Linking issue to this PR

2023-06-27 19:28 UTC, CircuitSacul requested changes

2023-06-27 19:28 UTC, CircuitSacul commented on src/middle-earth/str_and_repr.py
> +        """Repr prints the python code to create this python object."""
I wouldn't state this as fact. Even the stdlib doesn't follow this. Also it technically doesn't "print" anything.

Instead, I'd say something like "Generally, `__repr__` returns the code for creating the instance as a string".

2023-06-27 19:32 UTC, trag1c commented on src/middle-earth/str_and_repr.py
> +        """Repr prints the python code to create this python object."""
This! Alternatively "`__repr__` should return [...]".

2023-06-28 03:08 UTC, CircuitSacul commented on src/middle-earth/str_and_repr.py
> +        """repr returns string containing a printable representation of an object"""
strings are inherently printable?

maybe "Returns a string containing the code for creating the object"?

2023-06-28 03:10 UTC, isFakeAccount commented on src/middle-earth/str_and_repr.py
> +        """repr returns string containing a printable representation of an object"""
> strings are inherently printable?
> 
> maybe "Returns a string containing the code for creating the object"?

Yes, that's what the official docs say. https://docs.python.org/3/library/functions.html#repr

2023-06-28 03:11 UTC, CircuitSacul commented on src/middle-earth/str_and_repr.py
> +        """repr returns string containing a printable representation of an object"""
I still feel like it's a poor description

2023-06-28 03:13 UTC, isFakeAccount commented on src/middle-earth/str_and_repr.py
> +        """repr returns string containing a printable representation of an object"""
I disagree. Weird thing to nitpick on. Besides is it guaranteed that repr will always yield that object. 

> For many types, this function makes an attempt to return a string that would yield an object with the same value when passed to [eval()](https://docs.python.org/3/library/functions.html#eval)

The official docs do not say *for all types*.

2023-06-28 04:30 UTC, isFakeAccount commented
I rebased off the main branch which is why it looks like this

2023-07-19 21:21 UTC, MithicSpirit requested changes

2023-07-19 21:21 UTC, MithicSpirit commented on .gitignore
> +.idea/
No EOL at EOF

2023-07-19 21:21 UTC, MithicSpirit commented on src/middle-earth/str_and_repr.py
> +        """repr returns string containing a printable representation of an object"""
Even though it's not an absolute requirement I think that it should be indicated on the docstring.

2023-07-20 00:34 UTC, MithicSpirit requested changes

2023-07-20 00:34 UTC, MithicSpirit commented on src/middle-earth/str_and_repr.py
> +    my_class = MyCoolClass(value="© OpenAI ®")
I'm not too fond of this example string. Maybe something like `∫ f(x) dx` would be nice as a nod to [James's personal website](https://intfxdx.com/).

2023-07-20 00:34 UTC, MithicSpirit commented on src/middle-earth/str_and_repr.py
> +    # o = object()
Why isn't the repr of these examples printed out?

2023-07-20 00:34 UTC, MithicSpirit commented on .gitignore
> +
Now there's an extraneous newline. Not really a problem though.

2024-01-20 21:51 UTC, qexat commented on src/middle-earth/str_and_repr.py
> +    def __init__(self, *, value: str) -> None:
```suggestion
    def __init__(self, value: str) -> None:
```
Is making the argument keyword-only really necessary?

2024-01-22 17:24 UTC, PiCake314 approved these changes
Good example. Easy to follow and makes sense.

2024-01-22 17:56 UTC, Enderchief approved these changes
LGTM

2024-01-22 18:00 UTC, merged