Added Poetry
trag1c/mcoding-all-dunders pull request #32
Opened 2023-06-25 21:35 UTC by isFakeAccount

Added poetry :letsgoooo:

2023-06-27 19:18 UTC, CircuitSacul approved these changes

2023-06-27 19:37 UTC, trag1c reviewed
Add scripts for running CI and fixing code 👍

2023-06-27 19:37 UTC, trag1c commented on pyproject.toml
> +python = "^3.8"
I think we should be using Python 3.11+

2023-06-27 19:38 UTC, CircuitSacul commented on pyproject.toml
> +python = "^3.8"
I disagree, sometimes that would mean you have to install python3.11 (since poetry refuses to install anything). This could prevent some people from using poetry, since it will straight up refuse to work unless you install python 3.11.

2023-06-27 19:40 UTC, trag1c commented on pyproject.toml
> +python = "^3.8"
True. My intent was to encourage writing latest version code

2023-06-27 19:41 UTC, CircuitSacul commented on pyproject.toml
> +python = "^3.8"
Oh that's a good point. Now I agree, we should set it to 3.11

2023-06-28 03:37 UTC, isFakeAccount commented on pyproject.toml
> +python = "^3.8"
No, I am still on Python `3.10.6`. If this prevents me from installing packages and running code, I won't add it.

2023-06-28 04:44 UTC, James-Ansley commented
Not to be a Debbie Downer, but I don't really see the point of adding this to this project.

2023-06-28 04:54 UTC, MithicSpirit requested changes

2023-06-28 04:54 UTC, MithicSpirit commented on pyproject.toml
> +build-backend = "poetry.core.masonry.api"
Why does this have building configured? Is there any reason to build this project? Or does poetry just refuse to work if this isn't here?

2023-06-28 04:54 UTC, MithicSpirit commented on pyproject.toml
> +python = "^3.8"
I think that this should be set to at least whatever version supports all of the dunders in the list. Not sure which version that is.

2023-06-28 04:54 UTC, MithicSpirit commented on .gitignore
> +.idea/
Please end your files with newlines. I know it wasn't there before, but just always do it please.

2023-06-28 04:58 UTC, isFakeAccount commented on pyproject.toml
> +build-backend = "poetry.core.masonry.api"
Poetry automatically added this when I went through the steps. Not quite sure how essential this is.

2023-06-28 04:59 UTC, MithicSpirit commented on pyproject.toml
> +build-backend = "poetry.core.masonry.api"
How does its behavior change if you remove it, if at all?

2023-06-28 05:04 UTC, isFakeAccount commented on .gitignore
> +.idea/
> I think that this should be set to at least whatever version supports all of the dunders in the list. Not sure which version that is.

We are supposed to cover some 3.11 and 3.12 dunders. So python 3.12? 

- __div__
- __phello__
- __builtin___
- __ltrace__

2023-06-28 05:50 UTC, MithicSpirit commented on pyproject.toml
> +python = "^3.8"
> > I think that this should be set to at least whatever version supports all of the dunders in the list. Not sure which version that is.
> 
> We are supposed to cover some 3.11 and 3.12 dunders. So python 3.12?
> 
>     * **div**
> 
>     * **phello**
> 
>     * **builtin**_
> 
>     * **ltrace**

Oh lmao nvm. Maybe we should just remove the version ascription then (and the entire section in the config).

2023-06-28 09:46 UTC, Lunarmagpie commented on pyproject.toml
> +build-backend = "poetry.core.masonry.api"
This is just how it works in python land. Dumb thing to complain about, please resolve this.

2023-07-22 19:18 UTC, closed without merging