added __call__ method
trag1c/mcoding-all-dunders pull request #33
Opened 2023-06-26 14:55 UTC by 0lch4

2023-06-27 19:25 UTC, CircuitSacul approved these changes

2023-06-28 20:49 UTC, trag1c approved these changes

2023-07-07 17:44 UTC, bswck requested changes

2023-07-07 17:44 UTC, bswck commented on src/middle-earth/call.py
> +    def __call__(self, args):
Just a minor thing here, how about changing the name of `args` to `arg`?
Seems more consistent with the usage.

2023-07-07 17:44 UTC, bswck commented on src/middle-earth/call.py
> +        return args
I like the readability of this function. If you prefer, you may also use `functools.reduce`. Maybe mCoding would like an additional reference? Always some extra knowledge.

@jamesmurphy-mc?

2024-07-26 18:10 UTC, qexat approved these changes

2024-07-26 19:02 UTC, merged