added __hash__ method
trag1c/mcoding-all-dunders pull request #34
Opened 2023-06-26 23:02 UTC by 0lch4

2023-06-27 19:24 UTC, CircuitSacul requested changes

2023-06-27 19:24 UTC, CircuitSacul commented on src/middle-earth/hash.py
> +    # objects which compare equal must have the same hash value
This comment should be inside of the `__eq__` method, possibly as a docstring.

2023-06-27 19:25 UTC, trag1c commented on src/middle-earth/hash.py
> +    # objects which compare equal must have the same hash value
I'd put it inside `__eq__` but probably not as a docstring.

2023-06-27 22:18 UTC, trag1c approved these changes

2023-06-27 22:44 UTC, CircuitSacul approved these changes

2023-07-07 17:52 UTC, bswck approved these changes

2023-07-07 17:52 UTC, bswck commented on src/middle-earth/hash.py
> +    jacob_walker_clone = Citizen("Jacob", "Walker", "Cottage St")
Let's move it under `jacob_walker` maybe. But you don't have to.

2023-07-07 19:26 UTC, merged