Bool method
trag1c/mcoding-all-dunders pull request #36
Opened 2023-06-27 21:52 UTC by 0lch4

2023-06-27 22:50 UTC, CircuitSacul requested changes

2023-06-27 22:50 UTC, CircuitSacul commented on src/math-land/bool.py
> +    print(bool(PlainClass()))
I feel like a more readable example would be something like this:

```py
que = Queue()

if que:
    print("que is non-empty")
else:
    print("que is empty")

que.put("person")

if que:
    print("que is non-empty")
else:
    print("que is empty")

# you can also do this
print("bool(que) =", bool(que))

# class without a `__bool__` method are always Truthy
print("bool(PlainClass())=", bool(PlainClass()))
```

2023-06-27 22:50 UTC, CircuitSacul commented on src/math-land/bool.py
> +    def __init__(self, items: Sequence[T] | None = None) -> None:
Just a thought - does having advanced typing features distract from the main point (the dunder methods)?

cc @trag1c @jamesmurphy-mc

2023-06-27 22:52 UTC, trag1c commented on src/math-land/bool.py
> +    print(bool(PlainClass()))
Quick reminder that `print(f"bool(que) =", bool(que))` can be replaced with just `print(f"{bool(que) = }")`

2023-06-27 22:52 UTC, CircuitSacul commented on src/math-land/bool.py
> +    print(bool(PlainClass()))
ah right

2023-06-28 10:55 UTC, trag1c requested changes

2023-06-28 10:55 UTC, trag1c commented on src/math-land/bool.py
> +    # class without a `__bool__` method are always Truthy
```suggestion
    # instances of classes without a `__bool__` method are always truthy
```

2023-06-28 10:58 UTC, trag1c approved these changes

2023-06-28 15:38 UTC, trag1c commented on src/math-land/bool.py
> +    def __init__(self, items: Sequence[T] | None = None) -> None:
I personally don't mind it at all

2023-06-28 15:44 UTC, CircuitSacul approved these changes

2023-06-28 20:48 UTC, trag1c commented
Make black happy :+1:

2023-06-30 07:23 UTC, James-Ansley requested changes

2023-06-30 07:23 UTC, James-Ansley commented on src/math-land/bool.py
> +        return self.pop(0)
Should be `return self.items.pop(0)`?

2023-06-30 07:25 UTC, James-Ansley commented
How do people feel about possibly duplicating some dunders? I feel like this could be a really nice example showing that `__len__` is called if `__bool__` is not implemented – but I can see that `__len__` is already assigned.

2023-06-30 12:43 UTC, trag1c commented
> How do people feel about possibly duplicating some dunders? I feel like this could be a really nice example showing that `__len__` is called if `__bool__` is not implemented – but I can see that `__len__` is already assigned.

Feels inevitable

2023-07-07 17:49 UTC, bswck commented
> How do people feel about possibly duplicating some dunders? I feel like this could be a really nice example showing that `__len__` is called if `__bool__` is not implemented – but I can see that `__len__` is already assigned.

Very good idea IMO!

2023-07-07 17:55 UTC, bswck approved these changes

2023-07-07 19:23 UTC, merged