Comparisons using a 2D vector as example.
trag1c/mcoding-all-dunders pull request #4
Opened 2023-04-15 22:15 UTC by edsaac

It would cover

-  `__lt__`
- `__le__`
- `__eq__`
- `_ne__`
- `__gt__`
- `__ge__`

2023-04-15 23:54 UTC, Lunarmagpie commented on middle_earth/comparisons.py
> +    print(f"a ≥ √2 \t {a >= sqrt(2)}") # True
would prefer function names over non-ascii characters maybe. @trag1c ?

2023-04-15 23:55 UTC, trag1c commented on middle_earth/comparisons.py
> +    print(f"a ≥ √2 \t {a >= sqrt(2)}") # True
I think I would just do something like
```py
print(f"{a >= b = }")  # False
```

2023-04-15 23:57 UTC, trag1c requested changes
Please make docstrings use triple double quotes to comply with PEP 8 & 257

2023-04-15 23:57 UTC, trag1c commented on middle_earth/comparisons.py
> +    def __nq__(self, other: Self) -> bool:
```suggestion
    def __ne__(self, other: Self) -> bool:
```

2023-04-16 00:56 UTC, edsaac commented on middle_earth/comparisons.py
> +    print(f"a ≥ √2 \t {a >= sqrt(2)}") # True
I though so but figured that `a == b = True` didn't read as nice...  
Do y'all even want those little tests?

2023-04-16 01:10 UTC, trag1c commented on middle_earth/comparisons.py
> +    print(f"a ≥ √2 \t {a >= sqrt(2)}") # True
> I though so but figured that `a == b = True` didn't read as nice...

true

> Do y'all even want those little tests?

idk, it was never specified so I suppose they're optional

2023-04-16 01:59 UTC, trag1c commented
Could you put the file under `src/middle-earth/`?

2023-04-16 21:21 UTC, trag1c requested changes

2023-04-16 21:21 UTC, trag1c commented on src/middle-earth/comparisons.py
> +class Vector():
```suggestion
class Vector:
```

2023-04-16 21:21 UTC, trag1c commented on src/middle-earth/comparisons.py
> +            return self.mag >= other
I'm not sure if it's correct to annotate `other: Self` if it's still doing instance checks. Perhaps this should be just `other: Any`?

2023-04-17 11:32 UTC, edsaac commented on src/middle-earth/comparisons.py
> +            return self.mag >= other
or better to leave it simple as

```python
def __ge__(self, other: Self) -> bool:
    return self.mag >= other.mag
```

2023-04-17 15:37 UTC, trag1c commented on src/middle-earth/comparisons.py
> +            return self.mag >= other
> you mean something like this?
> 
> ```python
> def __ge__(self, other: Any) -> bool:
>     """Greater or equal than comparison"""
>     if isinstance(other, Vector):
>         return self.mag >= other.mag
>     elif isinstance(other, float):
>         return self.mag >= other
>     else:
>         raise TypeError
> ```

I'd leave the body the way it was and just change it to `other: Any`

2023-04-17 20:16 UTC, FuexFollets approved these changes

2023-04-17 20:39 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +    print("""Define three vectors a,b and c, such that
```suggestion
    print("""Define three vectors a, b and c, such that
```

2023-04-17 20:44 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +    def __ne__(self, other: Any) -> bool:
```suggestion
    def __ne__(self, other: Any) -> bool:
    """Not equal comparison"""
```

2023-04-17 20:46 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +
I believe latest Black dislikes empty lines like this.

2023-04-17 20:49 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +        self.mag = sqrt(self.x**2 + self.y**2)
I'd personally make `mag` a property (or a method, as it's doing a bit of math, other than just attribute access), or do something to make the class frozen, as right now all attributes can be modified, and doing so will almost certainly break the relationship between them.

But since this is just a dummy example, this might not be necessary, and would likely add some complexity to the example.

2023-04-17 20:50 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +    Comparisons between vectors are based on their magnitude
```suggestion
    Comparisons between vectors are based on their magnitude.
```

2023-04-17 21:01 UTC, trag1c commented on src/middle-earth/comparisons.py
> +
I don't think it matters that much; I'd probably remove it but this code is PEP8-compliant which is *good enough*

2023-04-17 21:09 UTC, trag1c commented on src/middle-earth/comparisons.py
> +        self.mag = sqrt(self.x**2 + self.y**2)
I think it might be good to go for a property

2023-04-17 22:24 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +        self.mag = sqrt(self.x**2 + self.y**2)
```suggestion

    @property
    def mag(self) -> float:
        return sqrt(self.x**2 + self.y**2)
```

2023-04-17 22:27 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +    Comparisons between vectors are based on their magnitude
I think ending the sentence with a period makes sense here, because the last sentence does end with a period.

2023-04-18 18:04 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +        return not self == other
Not sure if this would be a good idea, but this is likely what I'd do myself, to avoid repetition and such.

One could also do a `@typing.overload` that specifies that if `other: Vector`, the return is `float`, otherwise it's `Any`, but I think that'd bloat the example a lot.

```suggestion
    @staticmethod
    def _get_mag(other: Any) -> Any:
        return other.mag if isinstance(other, Vector) else other

    def __ge__(self, other: Any) -> bool:
        """Greater or equal than comparison"""
        return self.mag >= self._get_mag(other)

    def __gt__(self, other: Any) -> bool:
        """Greater than comparison"""
        return self.mag > self._get_mag(other)

    def __le__(self, other: Any) -> bool:
        """Less or equal than comparison"""
        return self.mag <= self._get_mag(other)

    def __lt__(self, other: Any) -> bool:
        """Less than comparison"""
        return self.mag < self._get_mag(other)

    def __eq__(self, other: Any) -> bool:
        """Equal comparison"""
        return self.mag == self._get_mag(other)

    def __ne__(self, other: Any) -> bool:
        """Not equal comparison"""
        return not self == other
```

2023-04-18 18:05 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +
I'll submit the suggestion anyways. It can be either accepted, or this conversation marked as resolved.
```suggestion
```

2023-04-18 18:07 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +    print(f"|c| = {c.mag:.5f}")
Maybe print `sqrt(2)` as well?
```suggestion
    print("\nPrint their magnitudes")
    print(f"|a| = {a.mag:.5f}")
    print(f"|b| = {b.mag:.5f}")
    print(f"|c| = {c.mag:.5f}")
    print(f"√2  = {sqrt(2)}")
```

2023-04-18 18:10 UTC, trag1c commented on src/middle-earth/comparisons.py
> +        return not self == other
Why is it a static method? 🤔

2023-04-18 18:13 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +        return not self == other
> Why is it a static method? thinking

Why wouldn't it be? It needs no reference to `cls` or to `self`. What do you think it should be?

2023-04-18 18:16 UTC, trag1c commented on src/middle-earth/comparisons.py
> +        return not self == other
I guess that's true. My thinking was that it's only ever used internally so it doesn't need to be static.

2023-04-18 18:18 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +        return sqrt(self.x**2 + self.y**2)
Add `from math import hypot`.
https://docs.python.org/3/library/math.html#math.hypot
```suggestion
        return hypot(self.x, self.y)
```

2023-04-18 18:19 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +from math import sqrt
Related to the other suggestion.
```suggestion
from math import hypot, sqrt
```

2023-04-18 18:20 UTC, MicaelJarniac commented on src/middle-earth/comparisons.py
> +        return sqrt(self.x**2 + self.y**2)
https://github.com/trag1c/mcoding-all-dunders/pull/4/files#r1170419004

2023-04-18 20:29 UTC, edsaac commented on src/middle-earth/comparisons.py
> +        return not self == other
Good idea!

2023-04-19 00:53 UTC, MithicSpirit requested changes
The entire idea of attempting to establish an ordering on **R**² (interpreted as a vector space) seems bad to me. With James being a math Ph.D., I feel like he won't be too fond of this example either, as it does not adhere to the axioms of partial/total orderings (particularly the lack of antisymmetry). In my opinion a different example should be used.

2023-04-19 00:53 UTC, MithicSpirit commented on src/middle-earth/comparisons.py
> +        return self.mag == self._get_mag(other)
Not fond of a definition of `__eq__` that's not compatible with `__hash__`. In the wild it might make sense, but I don't think that an educational resource like this should use it as an example.

2023-04-19 13:26 UTC, edsaac commented on src/middle-earth/comparisons.py
> +        return self.mag == self._get_mag(other)
I agree with this point, `__eq__` and `__ne__` would work better on a separate example that also involves `__hash__`.  

I think the other comparisons based on magnitude are totally fine -- the class can be renamed something else to avoid the implications of _vector_ as a concept.

2023-04-19 13:32 UTC, MithicSpirit commented on src/middle-earth/comparisons.py
> +        return self.mag == self._get_mag(other)
I think that maybe having `__eq__` present both in comparisons and in `__hash__` might be the best option, since it's relevant for both. If this is done then I think that this definition might be fine, maybe with a brief comment that this will have incorrect behavior with `__hash__`. Note that it seems like `__ne__` is not used for `__hash__` according to the [Python docs](https://docs.python.org/3/reference/datamodel.html#object.__hash__):
> The only required property is that objects which compare equal have the same hash value

2023-04-19 15:20 UTC, FuexFollets commented on src/middle-earth/comparisons.py
> +        return self.mag == self._get_mag(other)
Comparing floats for equality doesnt make too much sense since its very unpredictable. It might be a better idea to compare with a tolerance or use integers.

2023-04-21 14:21 UTC, edsaac commented
The class was renamed `Force` to avoid the `Vector` term, so comparisons can be rephrased as "is force $A$ stronger/weaker than force $B$?". 

This example would be more complete if the math dunders were implemented (`__add__`, etc.), but since that's on #10 already, so not sure if it's worth repeating.

2023-04-21 14:22 UTC, edsaac commented on src/middle-earth/comparisons.py
> +        return self.mag == self._get_mag(other)
Comparison with `math.isclose` was included.

2023-04-21 14:25 UTC, edsaac commented on middle_earth/comparisons.py
> +    print(f"a ≥ √2 \t {a >= sqrt(2)}") # True
What is the final say on non-ascii characters?  I'd rather leave them just for the aesthetics

2023-04-24 00:02 UTC, MicaelJarniac commented
Maybe `__abs__` could be part of this example too?

Something like:
```py
    def __abs__(self) -> float:
        return self.mag
```
And this could be used instead of the `_get_mag` method:
```py
    def __le__(self, other: Any) -> bool:
        return abs(self) <= abs(other)
```

2023-04-25 23:13 UTC, MithicSpirit approved these changes
lgtm

2023-04-25 23:27 UTC, trag1c commented on src/middle-earth/comparisons.py
> +        return not self == abs(other)
```suggestion
        return not self == other
```

2023-04-25 23:31 UTC, merged

2023-04-25 23:32 UTC, trag1c commented
Thanks! ❤️