Added doc
trag1c/mcoding-all-dunders pull request #6
Opened 2023-04-17 02:14 UTC by trag1c

2023-04-17 02:38 UTC, MithicSpirit requested changes
I think that this one might be interesting to show recommended formatting for longer docstring too, maybe also including info about parameters and all that.

Also, an important part of `__doc__` is how it interacts with other tooling like doc generation and `help()`, so maybe this should incorporate information on that too, but I think that this might be for @mCodingLLC to figure out.

2023-04-18 18:47 UTC, MithicSpirit commented
> I think that this one might be interesting to show recommended formatting for longer docstring too, maybe also including info about parameters and all that.
> 
> Also, an important part of `__doc__` is how it interacts with other tooling like doc generation and `help()`, so maybe this should incorporate information on that too, but I think that this might be for @mCodingLLC to figure out.

@jamesmurphy-mc

(org accounts don't get notifications)

2023-04-21 03:23 UTC, Lunarmagpie commented
Theres no reason to have so much code IMO. There just needs to be a function, class, and one method.

2023-05-04 13:51 UTC, qexat reviewed
property `area` does not have a docstring?
also, maybe one of the docstrings should be of the form
```py
"""
hello im a docstring
"""
```
to mention the newline thingy?

2023-05-04 14:14 UTC, qexat commented
> Can't we just annotate the class method `from_area` with `"Circle"` instead of `typing.Self`? Based on [PEP 484](https://peps.python.org/pep-0484/#forward-references).

`Self` is `Circle` and its subclasses as well, meaning that if you make a subclass of `Circle` called `SubCircle`, type-checkers will still consider the return type of `from_area` being `Circle` instead of `SubCircle`.

2023-06-17 19:00 UTC, trag1c commented
> I would like to show docstring for attribute and `help()` usage as well. Example of longer formatting on docstring for one of them would be good.

Aren't attribute docstrings only supported by editors? Also an issue with `help()` is that it's supposed to be used in the REPL and you can't see the docstrings and the help page at once in a case like:
```py
print("abs docstring": abs.__doc__)
help(Circle.from_area)
```
Should I include it like that nonetheless?

2023-06-20 07:19 UTC, Endercheif requested changes

2023-06-20 11:35 UTC, trag1c commented on src/module-mesa/doc.py
> +        return math.pi * self.radius**2
I didn't include a docstring for it since it's not obtainable but I guess I can add it :+1:
btw it doesn't quite make sense for a property to have a method-like description:
![67883](https://github.com/trag1c/mcoding-all-dunders/assets/77130613/f7b97585-3eb0-4f1a-8215-d9903f0e3341)

2023-06-20 19:57 UTC, Endercheif commented on src/module-mesa/doc.py
> +        return math.pi * self.radius**2
fair

2023-06-20 19:58 UTC, Endercheif approved these changes
looks to good me

2023-06-27 19:41 UTC, CircuitSacul approved these changes

2023-07-07 16:19 UTC, bswck requested changes
How about we show that subclasses do not inherit the `__doc__` attribute? People might think they do, in almost every other case.

My suggestion, if this idea seems good to you, would be to add a superclass to `Circle` (maybe `Shape`)? Then create some other subclass of `Shape` (maybe `Line`?) without a docstring, and print its class documentation to present that behavior. And maybe also show that virtual methods from superclasses keep their docstrings obtainable, unless overridden with a no-doc method implementation (which I think should change in `abc.ABC`... but that's an offtop here).

2023-07-07 16:19 UTC, bswck commented on src/module-mesa/doc.py
> +    print("Circle docstring:", Circle.__doc__)
At this point I would also print `Circle.__init__.__doc__` in order to prove unobtainability just to cover the case where `__doc__` is `None`, so that people know that this attribute is always guaranteed to be available as an optional string.

2023-07-10 18:31 UTC, bswck requested changes
Very cool example with the `UnitCircle` subclass. I've left just one more suggestion. :)

2023-07-10 18:31 UTC, bswck commented on src/module-mesa/doc.py
> +    print("Circle.from_area docstring:", Circle.from_area.__doc__)
Maybe also print `UnitCircle.from_area` docstring to show that it is `None`, because it did not default to the `Circle.from_area` docstring?

2023-07-10 18:32 UTC, trag1c commented on src/module-mesa/doc.py
> +    print("Circle.from_area docstring:", Circle.from_area.__doc__)
Sure!

2023-07-10 18:38 UTC, bswck requested changes
Just another minor suggestion.

2023-07-10 18:38 UTC, bswck commented on src/module-mesa/doc.py
>      print("Module docstring:", __doc__)
Maybe separate the `Circle`/`UnitCircle` examples from the module and `abs` docstrings in the output?
I suggest first print the `Circle`/`UnitCircle` docstrings examples, and then module docstring and `abs` docstring.
Or the other way around.

2023-07-10 20:31 UTC, bswck approved these changes

2023-07-10 20:31 UTC, bswck commented on src/module-mesa/doc.py
> +
Black probably complains about this

2023-07-10 20:32 UTC, trag1c commented on src/module-mesa/doc.py
> +
Oh I didn't even notice it failed

2023-07-10 20:35 UTC, merged