Added annotations
trag1c/mcoding-all-dunders pull request #7
Opened 2023-04-17 04:05 UTC by trag1c

I was also considering mentioning this but I wasn't entirely sure if it's that important:
> If Python stringizes your annotations for you (using `from __future__ import annotations`), and you specify a string as an annotation, the string will itself be quoted. In effect the annotation is quoted twice. For example:
> ```py
> from __future__ import annotations
> def foo(a: "str"): pass
> 
> print(foo.__annotations__)
> ```
> This prints `{'a': "'str'"}`. This shouldn’t really be considered a “quirk”; it’s mentioned here simply because it might be surprising.

From [Annotations Best Practices](https://docs.python.org/3/howto/annotations.html#annotations-quirks)

2023-04-17 20:17 UTC, MicaelJarniac commented on src/the-nest/annotations.py
> +        binary = f"0{binary}"
```suggestion
    binary = binary.rjust(math.ceil(len(binary) / 4) * 4, "0")
```

2023-04-17 20:17 UTC, MicaelJarniac commented on src/the-nest/annotations.py
> +    return sep.join(binary[i:i+4] for i in range(0, len(binary), 4))
```suggestion
    return sep.join("".join(s) for s in zip(*[iter(binary)] * 4))
```
This one is a bit of a stretch, though.
Based it on the "grouper" itertools recipe: https://docs.python.org/3/library/itertools.html#itertools-recipes

2023-04-17 20:20 UTC, trag1c commented on src/the-nest/annotations.py
> +        binary = f"0{binary}"
I think `binary = binary.zfill((len(binary) // 4 + 1) * 4)` works better

2023-04-17 20:34 UTC, trag1c commented on src/the-nest/annotations.py
> +    return sep.join(binary[i:i+4] for i in range(0, len(binary), 4))
I don't like this one, feels harder to read

2023-04-17 20:35 UTC, MicaelJarniac commented on src/the-nest/annotations.py
> +        binary = f"0{binary}"
Nice one!

2023-04-18 17:55 UTC, MicaelJarniac approved these changes

2023-04-18 18:33 UTC, MicaelJarniac commented
Wait! I found something cool.

2023-04-18 18:36 UTC, MicaelJarniac requested changes

2023-04-18 18:36 UTC, MicaelJarniac commented on src/the-nest/annotations.py
> +    return sep.join(binary[i:i+4] for i in range(0, len(binary), 4))
Add `from textwrap import wrap`.
```suggestion
    return sep.join(wrap(binary, 4))
```

2023-04-18 18:36 UTC, MicaelJarniac commented on src/the-nest/annotations.py
> +x: int
Related to the other suggestion.
```suggestion
from textwrap import wrap

x: int
```

2023-04-18 18:53 UTC, MicaelJarniac approved these changes

2023-04-21 03:22 UTC, Lunarmagpie approved these changes

2023-04-21 03:24 UTC, merged